name: Stats

on:
    schedule:
        - cron: 0 0 * * *
    push:
        branches:
            - gh-pages
        paths-ignore:
            - _data/stats.yml
jobs:
    build:
        name: getstats
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip3 install -U ruamel.yaml requests
            - name: Generate stats.yml
              shell: bash
              env:
                STATS_URL: ${{ secrets.StatsURL }}
              run: .github/workflows/stats.py "$STATS_URL"
            name: Commit files
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add _data/stats.yml
                git commit -m "Mise à jour des stats"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: gh-pages
